### ISSUE TITLE
org.apache.jena.riot.RiotException + Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by khoidt** [acoli-repo/conll-rdf#11]
Hi, 
while running the program from a Python script I stumbled upon the following errors. What should I do to fix this?

The command was the following:
```
run java -cp bin;lib/collection-0.7.jar;lib/commons-cli-1.4.jar;lib/commons-codec-1.11.jar;lib/commons-io-2.6.jar;lib/commons-lang3-3.4.jar;lib/httpclient-4.5.3.jar;lib/httpclient-cache-4.5.3.jar;lib/httpcore-4.4.6.jar;lib/jackson-annotations-2.9.0.jar;lib/jackson-core-2.9.0.jar;lib/jackson-databind-2.9.0.jar;lib/jcl-over-slf4j-1.7.25.jar;lib/jena-arq-3.6.0.jar;lib/jena-base-3.6.0.jar;lib/jena-core-3.6.0.jar;lib/jena-dboe-base-3.6.0.jar;lib/jena-dboe-index-3.6.0.jar;lib/jena-dboe-trans-data-3.6.0.jar;lib/jena-dboe-transaction-3.6.0.jar;lib/jena-iri-3.6.0.jar;lib/jena-shaded-guava-3.6.0.jar;lib/jena-tdb-3.6.0.jar;lib/jena-tdb2-3.6.0.jar;lib/jsonld-java-0.11.1.jar;lib/libthrift-0.10.0.jar;lib/log4j-1.2.17.jar;lib/slf4j-api-1.7.25.jar;lib/slf4j-log4j12-1.7.25.jar;lib/xercesImpl-2.11.0.jar;lib/xml-apis-1.4.01.jar org.acoli.conll.rdf.CoNLLStreamExtractor ../data/ ID FORM SEGM XPOSTAG HEAD DEPREL MISC
```
The CoNLL file was handled through `stdin`.
And this is the full error output:
```
org.apache.jena.riot.RiotException: [line: 15, col: 121] Triples not terminated by DOT	at org.apache.jena.riot.system.ErrorHandlerFactory$ErrorHandlerStd.fatal(ErrorHandlerFactory.java:147)
	at org.apache.jena.riot.lang.LangEngine.raiseException(LangEngine.java:148)
	at org.apache.jena.riot.lang.LangEngine.exceptionDirect(LangEngine.java:143)
	at org.apache.jena.riot.lang.LangEngine.exception(LangEngine.java:137)
	at org.apache.jena.riot.lang.LangEngine.expect(LangEngine.java:130)
	at org.apache.jena.riot.lang.LangEngine.expectOrEOF(LangEngine.java:119)
	at org.apache.jena.riot.lang.LangTurtleBase.expectEndOfTriplesTurtle(LangTurtleBase.java:265)
	at org.apache.jena.riot.lang.LangTurtle.expectEndOfTriples(LangTurtle.java:51)
	at org.apache.jena.riot.lang.LangTurtleBase.triples(LangTurtleBase.java:251)
	at org.apache.jena.riot.lang.LangTurtleBase.triplesSameSubject(LangTurtleBase.java:191)
	at org.apache.jena.riot.lang.LangTurtle.oneTopLevelElement(LangTurtle.java:46)
	at org.apache.jena.riot.lang.LangTurtleBase.runParser(LangTurtleBase.java:91)
	at org.apache.jena.riot.lang.LangBase.parse(LangBase.java:41)
	at org.apache.jena.riot.RDFParserRegistry$ReaderRIOTLang.read(RDFParserRegistry.java:206)
	at org.apache.jena.riot.RDFParser.read(RDFParser.java:338)
	at org.apache.jena.riot.RDFParser.parseNotUri(RDFParser.java:324)
	at org.apache.jena.riot.RDFParser.parse(RDFParser.java:273)
	at org.apache.jena.riot.RDFParserBuilder.parse(RDFParserBuilder.java:498)
	at org.apache.jena.riot.RDFDataMgr.parseFromReader(RDFDataMgr.java:880)
	at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:298)
	at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:283)
	at org.apache.jena.riot.adapters.RDFReaderRIOT.read(RDFReaderRIOT.java:62)
	at org.apache.jena.rdf.model.impl.ModelCom.read(ModelCom.java:298)
	at org.acoli.conll.rdf.CoNLL2RDF.conll2model(CoNLL2RDF.java:207)
	at org.acoli.conll.rdf.CoNLLStreamExtractor.main(CoNLLStreamExtractor.java:168)

Exception in thread "main" java.lang.NullPointerException
	at org.acoli.conll.rdf.CoNLLStreamExtractor.print(CoNLLStreamExtractor.java:240)
	at org.acoli.conll.rdf.CoNLLStreamExtractor.main(CoNLLStreamExtractor.java:175)
```

**Comment by chiarcos** [comment]
As it says,  "[line: 15, col: 121] Triples not terminated by DOT". This is  
an error in the data, not in the code. If it did not return information  
about what file or what data was read, we must create an issue to spell  
that information out.

Best,
Christian

Am .07.2018, 01:25 Uhr, schrieb khoidt <notifications@github.com>:

>
> Hi,
> while running the program from a Python script I stumbled upon the  
> following errors. What should I do to fix this?
> org.apache.jena.riot.RiotException: [line: 15, col: 121] Triples not  
> terminated by DOT	at  
> org.apache.jena.riot.system.ErrorHandlerFactory$ErrorHandlerStd.fatal(ErrorHandlerFactory.java:147)
> 	at  
> org.apache.jena.riot.lang.LangEngine.raiseException(LangEngine.java:148)
> 	at  
> org.apache.jena.riot.lang.LangEngine.exceptionDirect(LangEngine.java:143)
> 	at org.apache.jena.riot.lang.LangEngine.exception(LangEngine.java:137)
> 	at org.apache.jena.riot.lang.LangEngine.expect(LangEngine.java:130)
> 	at org.apache.jena.riot.lang.LangEngine.expectOrEOF(LangEngine.java:119)
> 	at  
> org.apache.jena.riot.lang.LangTurtleBase.expectEndOfTriplesTurtle(LangTurtleBase.java:265)
> 	at  
> org.apache.jena.riot.lang.LangTurtle.expectEndOfTriples(LangTurtle.java:51)
> 	at  
> org.apache.jena.riot.lang.LangTurtleBase.triples(LangTurtleBase.java:251)
> 	at  
> org.apache.jena.riot.lang.LangTurtleBase.triplesSameSubject(LangTurtleBase.java:191)
> 	at  
> org.apache.jena.riot.lang.LangTurtle.oneTopLevelElement(LangTurtle.java:46)
> 	at  
> org.apache.jena.riot.lang.LangTurtleBase.runParser(LangTurtleBase.java:91)
> 	at org.apache.jena.riot.lang.LangBase.parse(LangBase.java:41)
> 	at  
> org.apache.jena.riot.RDFParserRegistry$ReaderRIOTLang.read(RDFParserRegistry.java:206)
> 	at org.apache.jena.riot.RDFParser.read(RDFParser.java:338)
> 	at org.apache.jena.riot.RDFParser.parseNotUri(RDFParser.java:324)
> 	at org.apache.jena.riot.RDFParser.parse(RDFParser.java:273)
> 	at  
> org.apache.jena.riot.RDFParserBuilder.parse(RDFParserBuilder.java:498)
> 	at org.apache.jena.riot.RDFDataMgr.parseFromReader(RDFDataMgr.java:880)
> 	at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:298)
> 	at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:283)
> 	at  
> org.apache.jena.riot.adapters.RDFReaderRIOT.read(RDFReaderRIOT.java:62)
> 	at org.apache.jena.rdf.model.impl.ModelCom.read(ModelCom.java:298)
> 	at org.acoli.conll.rdf.CoNLL2RDF.conll2model(CoNLL2RDF.java:207)
> 	at  
> org.acoli.conll.rdf.CoNLLStreamExtractor.main(CoNLLStreamExtractor.java:168)
>
> Exception in thread "main" java.lang.NullPointerException
> 	at  
> org.acoli.conll.rdf.CoNLLStreamExtractor.print(CoNLLStreamExtractor.java:240)
> 	at  
> org.acoli.conll.rdf.CoNLLStreamExtractor.main(CoNLLStreamExtractor.java:175)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Prof. Dr. Christian Chiarcos
Applied Computational Linguistics
Johann Wolfgang Goethe Universität Frankfurt a. M.
60054 Frankfurt am Main, Germany

office: Robert-Mayer-Str. 10, #401b
mail: chiarcos@informatik.uni-frankfurt.de
web: http://acoli.cs.uni-frankfurt.de
tel: +49-(0)69-798-22463
fax: +49-(0)69-798-28931

**Comment by sagar-sehgal** [comment]
@khoidt did it work for you? I am facing an almost similar issue, but am not able to figure out the reason.

**Comment by max-ionov** [comment]
`conll-rdf` assumes that there is a number — a word id in the `HEAD` column, so when converting to RDF it generates the object of a `conll:HEAD` triple as `sentenceID_headValue`. So I think it _should_ crash for this data.
