### ISSUE TITLE
-lookback for CoNLLRDFUpdater

### ISSUE THREAD

**Issue by chiarcos** [acoli-repo/conll-rdf#14]
Request for the following functionality:
- flag -lookback with positive integer value $n
- When processing a nif:Sentence, provide access to the last $n preceding nif:Sentences.
- To facilitate parallelization, provide access to their *original* version, as read from stdin (before CoNLLRDF updates)
- Suggested data structure: a separate (RDF) Model (single Graph) with the fixed name <https://github.com/acoli-repo/conll-rdf/lookback>, populated from an Array/Vector of the most recent sentence models maintained during parsing time.
- The lookback graph is *not* returned, but only the default graph (where the current sentence resides).

This is necessary for coference processing, discourse and relation extraction. Quite important, actually.

**Comment by cfaeth** [comment]
Has been implemented as suggested. Please test.

**Comment by deshoe20** [comment]
Does not work error is:

org.apache.jena.riot.RiotNotFoundException: Not found:
        at org.apache.jena.riot.RDFParser.openTypedInputStream(RDFParser.java:376)
        at org.apache.jena.riot.RDFParser.parseURI(RDFParser.java:283)
        at org.apache.jena.riot.RDFParser.parse(RDFParser.java:277)
        at org.apache.jena.riot.RDFParserBuilder.parse(RDFParserBuilder.java:498)
        at org.apache.jena.riot.RDFDataMgr.parseFromURI(RDFDataMgr.java:890)
        at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:221)
        at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:190)
        at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:120)
        at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:111)
        at org.apache.jena.riot.adapters.RDFReaderRIOT.read(RDFReaderRIOT.java:76)
        at org.apache.jena.rdf.model.impl.ModelCom.read(ModelCom.java:263)
        at org.acoli.conll.rdf.CoNLLRDFUpdater$UpdateThread.loadBuffer(CoNLLRDFUpdater.java:192)
        at org.acoli.conll.rdf.CoNLLRDFUpdater$UpdateThread.run(CoNLLRDFUpdater.java:128)

tested with the following data https://pastebin.com/BrKqXKg6 and update query https://pastebin.com/6vdYR2dz

**Comment by cfaeth** [comment]
Fixed. System was not guessing TTL input correctly. Lookback graph now uses same Reader as default graph.
The test scenario now works. Modified the SPARQL test statement to display number of sentences in lookback graph: [https://pastebin.com/rs4FGySX]

Please test again.

**Comment by cfaeth** [comment]
Implemented Lookahead functionality.

works similar to lookback:
- lookback 4
  writes the last 4 sentences to graph <https://github.com/acoli-repo/conll-rdf/lookback>
- lookahead 4
  writes the following 4 sentences to graph <https://github.com/acoli-repo/conll-rdf/lookahead>
For lookahead and lookback two stacks need to be implemented and processed causing slightly more overhead. Speed impact is negligible. Yet, for very large scale look"around", memory limits might be met. Use with caution.

@deshoe20 please test. (I already tested using your aforementioned scenario on both lookX-graphs)

**Comment by deshoe20** [comment]
It seems that each current sentence is not part of the https://github.com/acoli-repo/conll-rdf/lookback or https://github.com/acoli-repo/conll-rdf/lookahead graph - is this intentional?

**Comment by cfaeth** [comment]
If you mean for lookahead/lookback = 2:
current sentence: s5_0
lookback: s3_0, s4_0
lookahead: s6_0, s7_0

s5_0 is intentionally not part of the lookahead and lookback graphs, as it is already in the default graph.

**Comment by deshoe20** [comment]
ok then.
