### ISSUE TITLE
support "-"-separated column labels in Formatter

### ISSUE THREAD

**Issue by chiarcos** [acoli-repo/conll-rdf#29]
Hyphens are valid characters in RDF properties, but not supported by CoNLLRDFFortmatter.

Currently, the following options don't work

-conll WORD POS PARSE NER COREF PRED PRED-ARGS

motivation: In the CoNLLStreamExtractor, PRED-ARGS is used as a multi-column label for semantic role annotations. This cannot be directly serialized back into CoNLL, but a SPARQL Update is necessary that contains values for all SRL columns as a single string, containing tabulators. For the sake of consistency with the CoNLLStreamExtractor, it should be possible to assign this property the name PRED-ARGS (or, XYZ-ARGS, or whatever the ARGS columns refer to). Current workaround is to name it PRED_ARGS (etc.).

error log:
Exception in thread "main" org.apache.jena.query.QueryParseException: Encountered " "-" "- "" at line 5, column 49.
Was expecting one of:
    <VAR1> ...
    <VAR2> ...
    "from" ...
    "where" ...
    "(" ...
    "{" ...

        at org.apache.jena.sparql.lang.ParserSPARQL11.perform(ParserSPARQL11.java:100)
        at org.apache.jena.sparql.lang.ParserSPARQL11.parse$(ParserSPARQL11.java:52)
        at org.apache.jena.sparql.lang.SPARQLParser.parse(SPARQLParser.java:34)
        at org.apache.jena.query.QueryFactory.parse(QueryFactory.java:147)
        at org.apache.jena.query.QueryFactory.create(QueryFactory.java:79)
        at org.apache.jena.query.QueryFactory.create(QueryFactory.java:52)
        at org.apache.jena.query.QueryFactory.create(QueryFactory.java:40)
        at org.apache.jena.query.QueryExecutionFactory.makeQuery(QueryExecutionFactory.java:564)
        at org.apache.jena.query.QueryExecutionFactory.create(QueryExecutionFactory.java:141)
        at org.acoli.conll.rdf.CoNLLRDFFormatter.printSparql(CoNLLRDFFormatter.java:572)
        at org.acoli.conll.rdf.CoNLLRDFFormatter.processSentenceStream(CoNLLRDFFormatter.java:790)
        at org.acoli.conll.rdf.CoNLLRDFFormatter.main(CoNLLRDFFormatter.java:725)

**Comment by leogott** [comment]
This is likely an issuer with the CommandLine Parsing. I'll address it in a related PR soon!
