### ISSUE TITLE
enforce UTF-8 read/write (instead of system locale)

### ISSUE THREAD

**Issue by chiarcos** [acoli-repo/conll-rdf#8]
The following error msg indicates that the RDF graph is being read with system locale. However, Turtle specs require it to be read as UTF-8. 

Proposed fix: enforce all read and write ops to use UTF-8.

UPDATE: Apparently, a Jena-side repair strategy is in place here that uses the system locale if reading as UTF-8 fails. Proposed fix: Explicitly check UTF-8 encoding for all input in order to elicit an informative error message.

16:15:48 INFO  CoNLLRDFUpdater      :: salt_2018-06-27.ttl into http://purl.org/acoli/salt/salt.owl
Exception in thread "main" org.apache.jena.atlas.RuntimeIOException: java.nio.charset.MalformedInputException: Input length = 1
        at org.apache.jena.atlas.io.IO.exception(IO.java:233)
        ... at org.apache.jena.rdf.model.impl.ModelCom.read(ModelCom.java:263)
        at org.acoli.conll.rdf.CoNLLRDFUpdater.loadGraph(CoNLLRDFUpdater.java:102)
        at org.acoli.conll.rdf.CoNLLRDFUpdater.main(CoNLLRDFUpdater.java:285)

**Comment by deshoe20** [comment]
Checkup on UTF-8 validation in connection with loading models from URIs -- loadGraph-->readInURI

**Comment by deshoe20** [comment]
implemented for update query input and graph input from URI
